# Generated by Django 4.2.5 on 2023-09-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employer_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('employer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.employer')),
            ],
        ),
    ]
