name: Starter Workflow Demo

on:
  workflow_dispatch:
    inputs:
      input1:
        type: string
        description: "Input 1"
      input2:
        type: string
        description: "Input 2"
      input3:
        type: choice
        description: "Environment"
        options:
          - test

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.input3 }}
    outputs:
      output1: ${{ steps.gather.outputs.VARS_JSON }}
      output2: ${{ steps.gather.outputs.TEST }}
      output3: ${{ steps.gather.outputs.ROLE }}
    steps:
      - name: Input 
        id: gather
        run: |
          echo "Gather environment related inputs"
          echo "VARS_JSON=${{ vars.VAR2 }}" >> "$GITHUB_OUTPUT"
          echo "TEST=${{ vars.VAR1 }}" >> "$GITHUB_OUTPUT"
          if [ ${{ inputs.input3 }} == "interop" ];then
            echo "ROLE=TST_ABP_${{ vars.VAR1 }}_FR" >> "$GITHUB_OUTPUT"
          fi

  job1:
    needs: build
    uses: jinujohny94/reusable/.github/workflows/resuable_workflow.yaml@main
    with:
      additional: "{\"INPUT1\":\"${{ inputs.input1 }}\", 
        \"INPUT2\":\"${{ inputs.input2 }}\",
        \"INPUT3\":\"${{ needs.build.outputs.output1 }}\",
        \"INPUT4\":\"${{ needs.build.outputs.output2 }}\",
        \"INPUT5\":\"${{ needs.build.outputs.output3 }}\"
        }"


    
    
