name: Starter Workflow Demo

on:
  workflow_dispatch:
    inputs:
      input1:
        type: string
        description: "Input 1"
      input2:
        type: string
        description: "Input 2"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      output1: ${{ steps.gather.outputs.VARS_JSON }}
    steps:
      - name: Input 
        id: gather
        env:
          TEST: ${{ vars.VAR1 }}
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "{\"INPUT1\":\"${{ inputs.input1 }}\", 
          \"INPUT2\":\"${{ inputs.input2 }}\",
          \"INPUT3\":\"${{ vars.VAR1 }}\",
          \"INPUT4\":\"${{ vars.VAR2 }}\",
          \"INPUT5\":\"${{ env.VARS_JSON }}\"}"

  job1:
    needs: build
    uses: jinujohny94/reusable/.github/workflows/resuable_workflow.yaml@main
    with:
      additional: "{\"INPUT1\":\"${{ inputs.input1 }}\", 
        \"INPUT2\":\"${{ inputs.input2 }}\",
        \"INPUT3\":\"${{ vars.VAR1 }}\",
        \"INPUT4\":\"${{ needs.build.outputs.output1 }}\"}"


    
    
