name: Starter Workflow Demo

on:
  workflow_dispatch:
    inputs:
      input1:
        type: string
        description: "Input 1"
      input2:
        type: string
        description: "Input 2"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: demo workflow job
        run: echo This is a demo start workflow
      - name: Input 
        run: |
          echo "{\"INPUT1\":\"${{ inputs.input1 }}\", 
          \"INPUT2\":\"${{ inputs.input2 }}\",
          \"INPUT3\":\"${{ vars.VAR1 }}\",
          \"INPUT4\":\"${{ vars.VAR2 }}\"}"

  job1:
    needs: build
    uses: jinujohny94/reusable/.github/workflows/resuable_workflow.yaml@main
    with:
      additional: "{\"INPUT1\":\"${{ inputs.input1 }}\", 
        \"INPUT2\":\"${{ inputs.input2 }}\",
        \"INPUT3\":\"${{ vars.VAR1 }}\",
        \"INPUT4\":\"${{ vars.VAR2 }}\"}"


    
    
