name : Test

on : 
  workflow_dispatch :
jobs :
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: composite
        uses: ./.github/actions/test123
