name : Test

on : 
  workflow_dispatch :


jobs :
  test_job :
    runs-on : ubuntu-latest

    steps :
      - name : Check out code
        uses: actions/checkout@v4
    
      - name : Run something
        uses : ./.github/actions/test123
        
